### PR TITLE
Added the new command 'odgi cover' to generate paths covering the graph

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
The implementation was taken, and slightly modified, from Jouni's code: [gbwtgraph](https://github.com/jltsiren/gbwtgraph). With this command, a specified number of paths can be generated for each graph component.
 
Here an example using a SARS-CoV-2 pangenome with 169 individuals, plus the gene annotations, which has 7 components. A visualization of the original graph is the following:
allvsall

I removed all the paths, and tried to generate new ones, specifying 10 paths per component (`-n` option), and displaying information about the components and the progress (`-d` option).

```
odgi build -g allvsall.no_paths.gfa -o - | odgi cover -i - -o allvsall.paths.odgi -n 10 -d && odgi viz -i allvsall.paths.odgi -o allvsall.paths.png -x 5000

SimpleCoverage: processing component 1 / 7, which has 1128 node(s) and it is cyclic.
Processed: 1
SimpleCoverage: processing component 2 / 7, which has 1 node(s) and it is acyclic.
Processed: 2
SimpleCoverage: processing component 3 / 7, which has 1 node(s) and it is acyclic.
Processed: 3
SimpleCoverage: processing component 4 / 7, which has 1 node(s) and it is acyclic.
Processed: 4
SimpleCoverage: processing component 5 / 7, which has 1 node(s) and it is acyclic.
Processed: 5
SimpleCoverage: processing component 6 / 7, which has 1 node(s) and it is acyclic.
Processed: 6
SimpleCoverage: processing component 7 / 7, which has 1 node(s) and it is acyclic.
Processed: 7
```
allvsall paths

Here the same test, but sorting the graph without paths before the paths generation (`-s` option in odgi build):

`odgi build -g allvsall.no_paths.gfa -o - -s | odgi cover -i - -o allvsall.s.paths.odgi -n 10 && odgi viz -i allvsall.s.paths.odgi -o allvsall.s.paths.png -x 5000`

allvsall s paths

The problem is that, depending on the user input (`-n` option), several duplicated paths are generated for small components. For 1-node components, it would be enough to impose to generate just 1 path, but, in general, it should be checked efficiently the number of unique paths for verifying if the max number of unique paths is reached during the execution, avoiding to create duplicated ones, or tolerating a max percentage of duplication.

### CODE REVIEW

**Comment by ekg** [comment]
:exploding_head:

**Comment by AndreaGuarracino** [comment]
Being more serious, removing the paths from the [yeast pangenome](https://github.com/ekg/yeast-pangenome), I have generated 50 paths per component (there is only one component), starting from the original result obtained from seqwish:

```
/usr/bin/time -v odgi cover -i Sc+Sp.pan.fpal10k.no_paths.og -o Sc+Sp.pan.fpal10k.no_paths.n50.k10.og -n 50 -k 3
	Command being timed: "odgi cover -i Sc+Sp.pan.fpal10k.no_paths.og -o Sc+Sp.pan.fpal10k.no_paths.n50.k10.og -n 50 -k 3"
	User time (seconds): 40.36
	System time (seconds): 0.99
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:41.36
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 1844556
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 682031
	Voluntary context switches: 9
	Involuntary context switches: 206
	Swaps: 0
	File system inputs: 555832
	File system outputs: 965640
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Sc+Sp pan fpal10k no_paths n50 k3

```
#mean_links_length: in_node_space 1.24592e+06, in_nucleotide_space 5.27887e+06
#sum_of_path_node_distances: in_node_space 2.49183e+06, in_nucleotide_space 2.51149e+06, num_penalties 3990755
```

Increasing the node window size (`-k` option), the algorithm becomes hungry of RAM, and the results 'seem' worse.

```
/usr/bin/time -v odgi cover -i Sc+Sp.pan.fpal10k.no_paths.og -o Sc+Sp.pan.fpal10k.no_paths.n50.k15.og -n 50 -k 15
	Command being timed: "odgi cover -i Sc+Sp.pan.fpal10k.no_paths.og -o Sc+Sp.pan.fpal10k.no_paths.n50.k15.og -n 50 -k 15"
	User time (seconds): 471.67
	System time (seconds): 11.88
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 8:03.56
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 42764496
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 5
	Minor (reclaiming a frame) page faults: 10911926
	Voluntary context switches: 13
	Involuntary context switches: 2062
	Swaps: 0
	File system inputs: 556416
	File system outputs: 2096136
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

Sc+Sp pan fpal10k no_paths n50 k15

```
#mean_links_length: in_node_space 1.54345e+06, in_nucleotide_space 6.69619e+06
#sum_of_path_node_distances: in_node_space 3.0869e+06, in_nucleotide_space 4.46863e+06, num_penalties 9639151
```

Here the results obtained removing the paths from a well sorted graph [Sc+Sp.pan.fpal10k.sYgs](https://github.com/vgteam/odgi/pull/136#issuecomment-667187256):

Sc+Sp pan fpal10k sYgs no_path n50 k3

```
#mean_links_length: in_node_space 134.192, in_nucleotide_space 515.662
#sum_of_path_node_distances: in_node_space 269.569, in_nucleotide_space 243.516, num_penalties 4014917
```

As expected, the take-home message is that if the graph is already well ordered, the generated paths are good too.

@subwaystation , I am imagining a test scenario where we will generate paths for path-less graphs, we will sort them with the path-guided algorithm, then we will throw out the paths, re-generate them, and finally re-order the graph with the path-guided algorithm again.

**Comment by AndreaGuarracino** [comment]
The minimum number of nodes to reach can be specified. For now I have imposed that the maximum number of paths that can be generated is equal to the number of nodes of the graph, to avoid the 'infinite' generation in particular/unexpected cases. There may be a better formula to compute the max number of paths, based on the specified minimum coverage.

**Comment by AndreaGuarracino** [comment]
I also set the default value for `node-window-size` to 2, and added an option to write coverage of nodes covered by generated paths to file, useful for views like the following to check what happened in the paths generation.

`--min-node-coverage 30, --node-window-size 2`
image
image

`--min-node-coverage 30, --node-window-size 20`
image
image

**Pull request merged**
