### PR TITLE
odgi stats: metrics for graph sorting goodness evaluation

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
New metrics for evaluating the goodness of a graph sorting. All the metrics are calculated considering all paths togheter, both in node space and nucleotide space. Moreover, they can be displayed for each path too.

The proposed metrics are:
- **mean nodes distance**: sum distances of all pairs of nodes in each path, dividing by the number of pairs considered.
- **mean link length**: sum link lengths in each path; it is possible to ignore gap links in the metric calculation;
- **sum of path node distances**: for each path, we iterate from node to node, summing their distances, and normalizing by the path length. If a link goes back in the linearized viewpoint of the graph, this is penalized (multiplying by 3 their distance); it is possible to penalize also the presence of reversed nodes (doubling their distance).

Little example, showing the metrics for each path too.
```
H	VN:Z:1.0
S	1	TTTTTTT
S	2	CCCC
S	3	AAAAAAAAAAAAAA
S	4	AAAAAAAAAAAAAAAAA
S	5	TTTTTT
S	6	GGGGGGGGGGG
L	1	-	3	-
L	1	+	2	+
L	2	+	4	+
L	4	+	5	+
L	4	+	6	+
L	2	+	6	+
L	6	+	1	+
P	Path1	1-,3-	*
P	Path2	1+,2+,4+,5+	*
P	Path3	4+,6+	*
P	Path4	1+,2+,6+,1+	*
```

```
odgi build -g 1.gfa -o - | odgi sort -i - -o 1.s.odgi
odgi build -g 1.gfa -o - | odgi sort -i - -Y -o 1.Y.odgi

odgi viz -i 1.s.odgi -o 1.s.png
odgi viz -i 1.Y.odgi -o 1.Y.png
```

image

**mean nodes distance**
`odgi stats -i 1.s.odgi -nP`

| path      | in_node_space | in_nucleotide_space | num_pairs |
|-----------|---------------|---------------------|-----------|
| Path1     | 2             | 11                  | 1         |
| Path2     | 2.33333       | 24                  | 6         |
| Path3     | 2             | 23                  | 1         |
| Path4     | 3.33333       | 32                  | 3         |
| all_paths | 2.54545       | 24.9091             | 11        |

`odgi stats -i 1.Y.odgi -nP`

| path      | in_node_space | in_nucleotide_space | num_pairs |
|-----------|---------------|---------------------|-----------|
| Path1	|4	|46	|1|
| Path2	|1.66667	|16.8333|	6|
| Path3	|2	|15|	1|
| Path4|	2	|21.3333|	3|
| all_paths|	2|	20.5455	|11|

**mean links length**
odgi stats -i 1.s.odgi -lP`

| path	|in_node_space	|in_nucleotide_space	|num_links_considered|
|-----------|---------------|---------------------|-----------|
| Path1	|3|	25	|1|
| Path2|	0.333333|	4.66667|	3|
| Path3	|1|	6|	1|
| Path4	|3|	32	|3|
| all_paths|	1.75	|17.625|	8|

`odgi stats -i 1.Y.odgi -lP`

| path	|in_node_space	|in_nucleotide_space	|num_links_considered|
|-----------|---------------|---------------------|-----------|
| Path1	|3|	32|	1|
| Path2	|1.33333	|11.6667	|3|
| Path3|	3|	32|	1|
| Path4|	2.33333|	21.3333	|3|
| all_paths|	2.125|	20.375|	8|

Ignoring gap links.

`odgi stats -i 1.s.odgi -lgP`

| path|	in_node_space|	in_nucleotide_space|	num_links_considered	|num_gap_links_ignored|
|-----------|---------------|---------------------|-----------|-----------|
| Path1	|0	|0|	0|	1|
| Path2	|0	|0|	0|	3|
| Path3	|0	|0|	0|	1|
| Path4	|6	|59	|1	|2|
| all_paths|	6|	59|	1|	7|

`odgi stats -i 1.Y.odgi -lgP`

| path|	in_node_space|	in_nucleotide_space|	num_links_considered	|num_gap_links_ignored|
|-----------|---------------|---------------------|-----------|-----------|
| Path1	| 3| 	32| 	1| 	0| 
|  Path2	| 2	| 17.5	| 2	| 1| 
|  Path3	| 3| 	32| 	1| 	0| 
|  Path4	| 2.33333	| 21.3333	| 3	| 0| 
|  all_paths| 	2.42857| 	23.2857| 	7| 	1| 

**sum of path node distances**

`odgi stats -i 1.s.odgi -sP`

|path|	in_node_space|	nodes|	in_nucleotide_space|	nucleotides|	num_penalties|
|-----------|---------------|---------------------|-----------|-----------|-----------|
| Path1	|1|	2|	0.52381|	21|	0|
| Path2	|1	|4	|1.23529	|34	|0|
| Path3	|1|	2|	0.821429|	28|	0|
| Path4	|5	|4	|6.62069	|29	|1|
| all_paths|	2.33333|	12|	2.39286|	112|	1|

`odgi stats -i 1.Y.odgi -sP`

|path|	in_node_space|	nodes|	in_nucleotide_space|	nucleotides|	num_penalties|
|-----------|---------------|---------------------|-----------|-----------|-----------|
|Path1	|6|	2|	6.57143|	21|	1|
| Path2	|2.25	|4	|2.67647	|34	|1|
| Path3	|3|	2|	1.60714|	28|	1|
| Path4	|3	|4	|4.41379	|29	|2|
| all_paths|	3.25|	12|	3.58929|	112|	5|

Penalizing also the presence of reversed nodes.

`odgi stats -i 1.s.odgi -srP`

|path|	in_node_space|	nodes|	in_nucleotide_space|	nucleotides|	num_penalties|	num_penalties_reversed_nodes|
|-----------|---------------|---------------------|-----------|-----------|-----------|-----------|
| Path1	|3	|2	|1.57143	|21	|0	|1|
| Path2	|1	|4|	1.23529|	34|	0|	0|
| Path3	|1	|2	|0.821429	|28	|0	|0|
| Path4	|5|	4|	6.62069|	29|	1|	0|
| all_paths	|2.66667	|12	|2.58929	|112	|1	|1|

`odgi stats -i 1.Y.odgi -srP`

|path|	in_node_space|	nodes|	in_nucleotide_space|	nucleotides|	num_penalties|	num_penalties_reversed_nodes|
|-----------|---------------|---------------------|-----------|-----------|-----------|-----------|
| Path1|	10|	2|	10.9524|	21|	1|	1|
| Path2	|2.25	|4	|2.67647	|34	|1	|0|
| Path3	|3	|2	|1.60714	|28	|1	|0|
| Path4	|3|	4|	4.41379|	29|	2|	0|
| all_paths|	3.91667|	12|	4.41071|	112|	5|	1|

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
Bigger examples with the strange pangenome with 169 SARS-CoV-2 genomes plus the annotations, showing only the overall metric for all paths together.

```
odgi build -g SARS-CoV-2.genbank.20200329.complete+annotations.gfa -o - | odgi sort -i - -o SARS-CoV-2.genbank.20200329.complete+annotations.s.odgi
odgi build -g SARS-CoV-2.genbank.20200329.complete+annotations.gfa -o - | odgi sort -i - -S -o SARS-CoV-2.genbank.20200329.complete+annotations.S.odgi
odgi build -g SARS-CoV-2.genbank.20200329.complete+annotations.gfa -o - | odgi sort -i - -Y -o SARS-CoV-2.genbank.20200329.complete+annotations.Y.odgi
odgi build -g SARS-CoV-2.genbank.20200329.complete+annotations.gfa -o - | odgi sort -i - -p bSnSnS -o SARS-CoV-2.genbank.20200329.complete+annotations.bSnSnS.odgi

odgi viz -i SARS-CoV-2.genbank.20200329.complete+annotations.s.odgi -o SARS-CoV-2.genbank.20200329.complete+annotations.s.png
odgi viz -i SARS-CoV-2.genbank.20200329.complete+annotations.S.odgi -o SARS-CoV-2.genbank.20200329.complete+annotations.S.png 
odgi viz -i SARS-CoV-2.genbank.20200329.complete+annotations.Y.odgi -o SARS-CoV-2.genbank.20200329.complete+annotations.Y.png
odgi viz -i SARS-CoV-2.genbank.20200329.complete+annotations.bSnSnS.odgi -o SARS-CoV-2.genbank.20200329.complete+annotations.bSnSnS.png
```

image

**mean_nodes_distance**

> sorting	path	in_node_space	in_nucleotide_space	num_pairs
> s	all_paths	1883.2	5992.62	2550306861
> S	all_paths	1911.03	7033.41	2550306861
> Y	all_paths	1871.03	9597.97	2550306861
> bSnSnS	all_paths	1890.18	6042.79	2550306861

**mean_links_length**

> path	in_node_space	in_nucleotide_space	num_links_considered
> s	all_paths	1.44324	7.62266	1219304
> S	all_paths	2.56772	15.3774	1219304
> Y	all_paths	5.58725	27.2472	1219304
> bSnSnS	all_paths	3.47429	14.346	1219304

> path	in_node_space	in_nucleotide_space	num_links_considered	num_gap_links_ignored
> s	all_paths	3.03083	16.3189	560892	658412
> S	all_paths	3.5372	21.319	874845	344459
> Y	all_paths	8.1129	37.9902	835739	383565
> bSnSnS	all_paths	3.9624	16.3961	1063397	155907

**sum_of_path_node_distances**

> path	in_node_space	nodes	in_nucleotide_space	nucleotides	num_penalties
> s	all_paths	4.0655	1219496	4.70744	5118592	570
> S	all_paths	5.54508	1219496	7.1333	5118592	369264
> Y	all_paths	11.7014	1219496	12.7748	5118592	205135
> bSnSnS	all_paths	6.9326	1219496	6.99109	5118592	587900

> path	in_node_space	nodes	in_nucleotide_space	nucleotides	num_penalties	num_penalties_reversed_nodes
> s	all_paths	4.0655	1219496	4.70744	5118592	570	0
> S	all_paths	5.54508	1219496	7.1333	5118592	369264	0
> Y	all_paths	11.7014	1219496	12.7748	5118592	205135	0
> bSnSnS	all_paths	6.9326	1219496	6.99109	5118592	587900	0

**Comment by AndreaGuarracino** [comment]
@subwaystation, I think the metrics that well correlate with the 'good-lookingness for the eyes' are the **mean_links_length** and **sum_of_path_node_distances** (indeed, they are not so different in their formulation), and they are not so much expensive to compute.

The **mean_nodes_distance** is heavy to computer in its exact formulation (the computational complexity is quadratical respect to the number of nodes in the path), and it doesn't seem so helpful. Unless there are scenarios where it could be useful, we could re-formulate this metric in a more oriented eyes-way, or remove it at all.

**Comment by AndreaGuarracino** [comment]
I generated with SPOA pangenome using [HLA-zoo](https://github.com/ekg/HLA-zoo)'s datasets. For all the dataset, the topological sort wins.

I report two examples to show you how the metrics's values changes respect to the sorting algorithm. In the odgi viz screenshots, the sortings are arranged from top to bottom as they are from left to right in the plots with the values ​​of the metrics (S, Y, bSnSnS, S). The *mean_nodes_distance* still doesn't seem to relate to what our eyes want.

# A-3105
A-3105
A-3105 bg

# F-3134
F-3134
F-3134 bg

**Comment by josiahseaman** [comment]
This is very encouraging, Andrea. Thank you for working on this. I can
think of two concepts for multiple sequence alignment scoring that would be
useful here. One is to have separate scores for starting a gap versus
making the Gap larger, so count the number of links and give it a
multiplier and then also and on top of that distances to double penalize
rearrangements.

The second observation is a bit more vague. I've noticed batches of
rearrangements get moved to the same place such as all the orphaned starts
in SARS-CoV-2 ending up at the end of the pangenome. I only wonder if there
is a way to identify the shared bundle of Links and move them as a set to
the correct area where they should be?  We discussed this a bit with
unrolling, where you traverse two steps of a link and see if it returns
back to the start again, then you have very strong reason to think there's
a pair of complementary links (+587, -586) in pangenome coordinates. That's
all for now.  Good luck!

**Comment by AndreaGuarracino** [comment]
Hi Josiah, I'm not sure I got your points. At the moment the gaps are penalized based on their length, and if link goes back in the linear graph, the penalty is multiplied by 3, therefore we strongly penalize these rearrangements. The second point seems more related on the sorting step, not the sorting evaluation, but we are working also to improve that part.

**Comment by AndreaGuarracino** [comment]
# [yeast-pangenome](https://github.com/ekg/yeast-pangenome) example
I report the results for the pangenome obtained filtering the alignments shorter than 10kbp.

In this case, I didn't calculate the mean nodes distance metric. I propose to eliminate or modify this metric. I've added more sorting pipelines, also the `-p sYgs` as suggested by @ekg.

As you can see, there a peak with the `-p sY` sorting pipeline, which crushes the values ​​for the other pipelines in the plots.

Sc+Sp pan fpal10k withY

Looking at what happened, we have a pangenome above a black sea:

#### Sc+Sp.pan.fpal10k.sY.x2000.png
Sc+Sp pan fpal10k sY x2000

By removing that peak, the metric values ​​for the other pipelines become recognizable:

Sc+Sp pan fpal10k

Looking at the metrics, the `-p sYgs` and `-p sbSnSnS` seem to give the best results.

#### Sc+Sp.pan.fpal10k.sYgs.x2000.png
Sc+Sp pan fpal10k sYgs x2000

#### Sc+Sp.pan.fpa10k.sbSnSnS.x2000.png
Sc+Sp pan fpal10k sbSnSnS x2000

@subwaystation, these results appear very different for my eyes, but this diversity does not seem to be reflected in big differences in values ​​of some metrics. Maybe we are still missing something that with the current metrics is not considered.

**Comment by AndreaGuarracino** [comment]
I updated an option for the *sum of path node distances* metric: now it is possible to count and penalize the links which connect nodes in different orientation. It is useful to analyze cases where entire paths are reversed 'in a good way', like in the last yeast example. In the `sYgs` pipeline (the binned image on the left, bin width 1000), the grooming seems to help a lot the topologial sort in the last step, comparing it with the same dataset, but removing the grooming step (the binned image on the right, bin width 1000).

| sorting | path      | in_node_space    | in_nucleotide_space | nodes    | nucleotides | num_penalties | num_penalties_different_orientation |
|---------|-----------|------------------|---------------------|----------|-------------|---------------|-------------------------------------|
| sYgs    | all_paths | 258.005 	  	  	  	  	 | 236.857             | 34132379 | 143169270   | 9764695       | 391                                 |
| sYs     | all_paths | 1560.72          | 1471.64             | 34132379 | 143169270   | 1274723       | 148225                              |
| sbSnSnS | all_paths | 165.959          | 160.439             | 34132379 | 143169270   | 9537252       | 148225                              |

image

The result for the `sbSnSnS` pipeline has lower metric values, but it seems to be due to a lot of short links. In the following, the binned image of this result, with bin width 1000.

image

**Comment by subwaystation** [comment]
Great Job @AndreaGuarracino! Now we can even distinguish between the different yeast sorting results:+1: 
Happy to merge it in.

**Pull request merged**
