### PR TITLE
odgi viz display path names

### LINKED ISSUE #33: viz should display path names
This is tricky. We want to be able to see the path names, but this requires directly writing into the PNG image. An alternative is to pull in cairo and write vector graphics over the image. That's also tricky, and introduces more (very complicated and oldschool) dependencies. I'll look into alternatives.

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
When ready, it will resolve #33 

DRB1-3123 edyeet s500n20p75a75 sYgY G100

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
Visualization of a yeast pangenome

yeast

**Comment by subwaystation** [comment]
> Added an option to color the background of path names to facilitate their association with the corresponding paths on the right.
> 
> yeast

THIS LOOKS SPLENDID!

**Comment by AndreaGuarracino** [comment]
Improved performance when a subset of all paths is displayed.

Tests with the new functionalities introduced in #184, looking at different groups of chromosomes for all the 12 yeast strains with different visualization modes.

xxx bz


xxx du


xxx bm

**Comment by AndreaGuarracino** [comment]
Bigger test with the B1phi1 data (2196 paths).

run1 B1phi1 i1 seqwish

Zoom at the end:

run1 B1phi1 i1 seqwish Y G50 x

**Pull request merged**
