### PR TITLE
removed pinchesAndCacti and sonLib in order to prepare odgi for a bio…

### PR DESCRIPTION
**Pull request by subwaystation**
…conda packaging. This should bring us a step further in #75 .
I can still build ODGI. `odgi test` runs through, too.

### CODE REVIEW

**Comment by ekg** [comment]
Fine by me. Are you happy with this? Should I merge it?

**Comment by subwaystation** [comment]
Yes, please. Thanks!

**Comment by subwaystation** [comment]
Or we wait until the code in this branch builds in bioconda?

**Comment by ekg** [comment]
OK! Let's wait on the bioconda build. You can pull in from here to bioconda right?

**Comment by subwaystation** [comment]
That's what I am going to ask. So far they only tried to pull the current release v0.1.

**Comment by subwaystation** [comment]
As this worked as intended, could you please merge @ekg?

**Pull request merged**
