### PR TITLE
Adding source files for glossary, figures

### PR DESCRIPTION
**Pull request by ctcisar**
Added source files as requested in https://github.com/vgteam/odgi/pull/72

### CODE REVIEW

**Comment by ekg** [comment]
Please also include the GFA for the example graph that's currently storred in odgi format, and remove the .odgi format file.

In parallel, I'll need to update the serialization method in pyhton space to write the magic number.

**Comment by ctcisar** [comment]
I removed the included odgi file and changed the tutorial text to address this, the source file (`cactus-brca2.vg`) was added in a previous commit.

**Comment by ekg** [comment]
Please add the GFA for this .vg file. The .vg file isn't going to be usable
without vg, and is also liable to change.

GFA is very unlikely to become illegible in the near future.

**Comment by ctcisar** [comment]
I don't have a GFA file for this, and I don't see a flag to convert this with "vg convert".  How to I convert this to a GFA file?

**Comment by ekg** [comment]
vg view defaults to GFA output:

vg view file.vg >file.gfa

**Comment by ctcisar** [comment]
Ok, I added it.

**Comment by ekg** [comment]
Thank you :)

**Pull request merged**
