### PR TITLE
Odgi sort psgd k default val eval

### PR DESCRIPTION
**Pull request by subwaystation**
I will evaluate if changing `-k/--path-sdg-zipf-space` to the longest path length is benificial.

### CODE REVIEW

**Comment by ekg** [comment]
We might also want to set the quantization step to be larger, to reduce the
computation time spent on zipf distributions.

**Comment by subwaystation** [comment]
## HLA zoo

eval

I think most of the fluctuations are a result of the stochastic nature of the P-SGD. We don't get substantial worsings, so all is fine.

**Comment by subwaystation** [comment]
## yeast 112

### timings

```
## master
[odgi::path_linear_sgd] calculating linear SGD schedule (3.98373e-10 1 30 0 0.01)
[odgi::path_linear_sgd] calculating zetas for 1091 zipf distributions

        User time (seconds): 565.65
        System time (seconds): 3.04
        Percent of CPU this job got: 2235%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:25.44


## only k
[odgi::path_linear_sgd] calculating linear SGD schedule (3.98373e-10 1 30 0 0.01)
[odgi::path_linear_sgd] calculating zetas for 16659 zipf distributions

        User time (seconds): 1682.08
        System time (seconds): 3.79
        Percent of CPU this job got: 2316%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:12.78


## k and path_sgd_zipf_space_quantization_step=10000
[odgi::path_linear_sgd] calculating linear SGD schedule (3.98373e-10 1 30 0 0.01)
[odgi::path_linear_sgd] calculating zetas for 1157 zipf distributions

        User time (seconds): 598.51
        System time (seconds): 3.37
        Percent of CPU this job got: 2200%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:27.35
```

### stats
master
```
#mean_links_length
path	in_node_space	in_nucleotide_space	num_links_considered
all_paths	6.75682	150.625	2500176
#sum_of_path_node_distances
path	in_node_space	in_nucleotide_space	nodes	nucleotides	num_penalties	num_penalties_different_orientation
all_paths	12.9017	9.31061	2500288	83530630	939458	0
```
k
```
#mean_links_length
path	in_node_space	in_nucleotide_space	num_links_considered
all_paths	5.95801	129.971	2500176
#sum_of_path_node_distances
path	in_node_space	in_nucleotide_space	nodes	nucleotides	num_penalties	num_penalties_different_orientation
all_paths	11.3192	8.22508	2500288	83530630	830803	0
```
path_sgd_zipf_space_quantization_step
```
#mean_links_length
path    in_node_space   in_nucleotide_space     num_links_considered
all_paths       5.73531 126.226 2500176
#sum_of_path_node_distances
path    in_node_space   in_nucleotide_space     nodes   nucleotides     num_penalties   num_penalties_different_orientation
all_paths       10.8781 7.99676 2500288 83530630        829705  0
```

### viz
master
cerevisiae pan fa gz pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0 5-N seqwish gfa og Y_k_default viz

k
cerevisiae pan fa gz pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0 5-N seqwish gfa og Y_k_max_path_length viz

k && path_sgd_zipf_space_quantization_step
cerevisiae pan fa gz pggb-s10000-p90-n5-a90-K16-k8-w30000-j5000-e5000-I0 5-N seqwish gfa og Y_k_max_path_length viz path_sgd_zipf_space_quantization_step=10000

### Summary
There is not a negative quantifiable effect regarding the linearization of a pangenome graph using `k=max_path_length` and `path_sgd_zipf_space_quantization_step=10000`. However, only setting `k=max_path_length` the `calculating zetas` step is slowing down significantly. I expect for larger graphs like Chr20 or even Chr1, we might need to find a formula where the `path_sgd_zipf_space_quantization_step` is coupled to the value of `k`.

**Comment by subwaystation** [comment]
> We might also want to set the quantization step to be larger, to reduce the computation time spent on zipf distributions.

@ekg 
Did you mean
```
      -I[N],
      --path-sgd-zipf-space-max=[N]     the maximum space size of the Zipfian
                                        distribution beyond which quantization
                                        occurs (default: 1000)
```
OR
```
      -l[N],
      --path-sgd-zipf-space-quantization-step=[N]
                                        quantization step when the maximum space
                                        size of the Zipfian distribution is
                                        exceeded (default: 100)
```
?
So far, I evaluated the latter one.

**Comment by AndreaGuarracino** [comment]
The yeast pangenome is funny, perhaps too stringent parameters were applied during the alignment. I would try a more 'dirty' pangenome.

I always find interesting that the quantization tends to help, a lot in terms of time of course, but also in terms of final sorting-goodness metric, albeit slightly in this case.

**Comment by ekg** [comment]
We should use a higher quantization step size to counteract the cost of
computing all those zipfs.

**Comment by subwaystation** [comment]
So I am on the right track. Thanks!

**Comment by AndreaGuarracino** [comment]
An easy way would be to limit the maximum number of zipfian distributions to calculate.

I changed the dependencies present between the parameters: if the quantization step is not specified by the user, it is calculated in such a way that the maximum number of zipfian distributions is about the default one (for now 4000).

I also added a new parameter to control the maximum number of distributions allowed (`-y/--path-sgd-zipf-max-num-distributions`). In this way we can more easily decide how much we are willing to pay computationally when calculating the distributions.

We can play around with both ways to control the quantization (`-l/--path-sgd-zipf-space-quantization-step` or `-y/--path-sgd-zipf-max-num-distributions`). Probably, the new parameter will replace the previous one, also simplifying a bit the code and the `odgi sort` interface.

**Comment by subwaystation** [comment]
# Evaluation of `-y` and `-I`

## HLA Zoo, 1 RUN

### sum_of_path_node_distances nuc_space
`-y default` `-I default` vs. `-y 10` `-I 10`
k_y10_I10
`-y 10` `-I 10` vs. `-y 1` `-I 1`
y10_I10_y1_I1
### Some example visualizations from DRB1-3123.
`-y default` `-I default`
DRB1-3123 fa gz seqwish gfa og Y_k_max_path_length viz
`-y 10` `-I 10`
DRB1-3123 fa gz seqwish gfa og Y_k_max_path_length_y10_I10 viz
`-y 1` `-I 1`
DRB1-3123 fa gz seqwish gfa og Y_k_max_path_length_y1_I1 viz

### Summary
No clear difference between `-y default` `-I default` and `-y 10` `-I 10`. But `-y 1` `-I 1` is obviously worse than `-y 10` `-I 10`.

! Results for Chr20 are currently processed, stay tuned!

**Comment by subwaystation** [comment]
## HPPY1_Chr20, Mean of 3 RUNs

### sum_of_path_node_distances nuc_space
HPPY1_Chr20
The red line is the mean, the green line the median.

### Some example visualizations
`-y 1000`
hppy1_sub8+chm13+h38-chr20 fa gz gfa og Y_k_max_path_length_y_1000_1 viz

`-y 1000 -I 100`
hppy1_sub8+chm13+h38-chr20 fa gz gfa og Y_k_max_path_length_y_1000_I100_1 viz

`-y 500 -I 100`
hppy1_sub8+chm13+h38-chr20 fa gz gfa og Y_k_max_path_length_y_500_I100_1 viz


`-y 100 -I 100`
hppy1_sub8+chm13+h38-chr20 fa gz gfa og Y_k_max_path_length_y_100_I100_1 viz


`-y 50 -I 50`
hppy1_sub8+chm13+h38-chr20 fa gz gfa og Y_k_max_path_length_y_50_I50_1 viz

`-y10 -I 10`
hppy1_sub8+chm13+h38-chr20 fa gz gfa og Y_k_max_path_length_y_10_I10_1 viz

### Summary

Taking a look at the `sum_of_path_node_distances nuc_space` the combination of smaller `-y` with a smaller `-I` produces the most linearized graphs.
However, in the visualizations of `-y 50 -I 50` and `-y10 -I 10`, there seem to be some unresolved overlaps, that are visualized. So these parameter settings might not be ideal. From `-y 100 -I 100` on, the results make sense again.

**Comment by subwaystation** [comment]
# TOTAL SUMMARY

The best parameter combination in terms of quality is `-y 100 -I 100`. It is also the 3rd fastest and faster than all runs with `-y > 100`.

**Comment by AndreaGuarracino** [comment]
I am impressed with how quantization can squeeze performance, seemingly for free, also improving the sorting quality, albeit slightly.

More tricky chromosomes, we are coming.

**Pull request merged**
